<?php

namespace AppBundle\Repository;

/**
 * AaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AaeRepository extends \Doctrine\ORM\EntityRepository
{
}
