<?php

namespace AppBundle\Repository;

/**
 * AerienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AerienRepository extends \Doctrine\ORM\EntityRepository
{
}
