<?php

namespace AppBundle\Repository;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends \Doctrine\ORM\EntityRepository
{
}
