<?php

namespace AppBundle\Repository;

/**
 * ChocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChocRepository extends \Doctrine\ORM\EntityRepository
{
}
