<?php

namespace AppBundle\Repository;

/**
 * EquipementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementRepository extends \Doctrine\ORM\EntityRepository
{
}
