<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Equipement;
use AppBundle\Entity\Operation;
use Doctrine\ORM\EntityRepository;

/**
 * EquipementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementRepository extends EntityRepository
{
    /**
     * @param Operation $operation
     * @param $measureNumber
     * @param $equipementType
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByIdOfSheetAndOperation(Operation $operation, $measureNumber, $equipementType){
        $this->getEntityManager()
            ->getRepository(Equipement::class)
            ->createQueryBuilder('a')
            ->where('a.measureNumber = :measureNumber')
            ->andWhere('a.equipementType = :equipementType')
            ->andWhere('a.operation = :operation')
            ->setParameters(
                [
                    'measureNumber' => $measureNumber,
                    'equipementType' => $equipementType,
                    'operation' => $operation,
                ]
            )
            ->getQuery()
            ->getOneOrNullResult();
    }
}
