<?php

namespace AppBundle\Repository;

/**
 * ForeignerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForeignerRepository extends \Doctrine\ORM\EntityRepository
{
}
