<?php

namespace AppBundle\Repository;

use AppBundle\Entity\NoiseSource;
use AppBundle\Entity\Operation;

/**
 * \class NoiseSourceRepository
 * @ingroup Materiel
 * @package AppBundle\Repository
 *
 * This class was generated by the Doctrine ORM.
 */
class NoiseSourceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @returns the 1st noise source registered for an agency
     * @param Operation $operation
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findFirstByOperationAgency(Operation $operation){
        return $this->getEntityManager()
            ->getRepository(NoiseSource::class)
            ->createQueryBuilder('NS')
            ->where('NS.agency = :operationAgency')
            ->setMaxResults(1)
            ->setParameters(
                [
                    'operationAgency' => $operation->getAgency(),
                ]
            )
            ->getQuery()
            ->getResult();
    }

}
