<?php

namespace AppBundle\Repository;

/**
 * NoiseSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoiseSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
