<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Aae;
use AppBundle\Entity\Operation;
use AppBundle\Entity\Pictures;
use Doctrine\ORM\EntityRepository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicturesRepository extends EntityRepository
{
    /**
     * @param $name
     * @param Operation $operation
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByName($name, Operation $operation){
        return $this->getEntityManager()
            ->getRepository(Pictures::class)
            ->createQueryBuilder('p')
            ->where('p.name = :name')
            ->andWhere('p.operation = :operation')
            ->setParameters(
                [
                    'name' => $name,
                    'operation' => $operation,
                ]
            )
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param Operation $operation
     * @return mixed
     */
    public function getPictureByOperationOrder(Operation $operation){
        return $this->getEntityManager()
            ->getRepository(Pictures::class)->createQueryBuilder('r')
            ->where('r.operation = :operation')
            ->setParameter('operation', $operation)
            ->orderBy('r.position')
            ->getQuery()
            ->getResult();
    }
}
