<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Operation;
use AppBundle\Entity\Results;
use Doctrine\ORM\EntityRepository;

/**
 * \class ResultsRepository
 * @ingroup Acoustique
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultsRepository extends EntityRepository
{
    /**
     * @param Operation $operation
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByOperation(Operation $operation){
        return $this->getEntityManager()
            ->getRepository(Results::class)
            ->createQueryBuilder('a')
            ->where('a.operation = :operation')
            ->setParameter('operation', $operation)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
