<?php

namespace AppBundle\Repository;

/**
 * ReverbAccessoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReverbAccessoryRepository extends \Doctrine\ORM\EntityRepository
{
}
