<?php

namespace AppBundle\Repository;

/**
 * ShockmachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShockmachineRepository extends \Doctrine\ORM\EntityRepository
{
}
