<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Operation;
use AppBundle\Entity\Shock;
use Doctrine\ORM\EntityRepository;

/**
 * ChocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShockRepository extends EntityRepository
{
    /**
     * @param Operation $operation
     * @param $idOfSheet
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByIdOfSheetAndOperation(Operation $operation, $idOfSheet){
        $this->getEntityManager()
            ->getRepository(Shock::class)
            ->createQueryBuilder('a')
            ->where('a.idOfSheet = :idOfSheet')
            ->andWhere('a.operation = :operation')
            ->setParameters(
                [
                    'idOfSheet' => $idOfSheet,
                    'operation' => $operation,
                ]
            )
            ->getQuery()
            ->getOneOrNullResult();
    }
}
