<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Software;
use AppBundle\Entity\Operation;

/**
 * \class SoftwareRepository
 * @ingroup Materiel
 * @package AppBundle\Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftwareRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @returns the 1st software registered for an agency
     * @param Operation $operation
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findFirstByOperationAgency(Operation $operation){
        return $this->getEntityManager()
            ->getRepository(Software::class)
            ->createQueryBuilder('s')
            ->where('s.agency = :operationAgency')
            ->setMaxResults(1)
            ->setParameters(
                [
                    'operationAgency' => $operation->getAgency(),
                ]
            )
            ->getQuery()
            ->getResult();
    }
}
