app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /ra1999

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /ra1999

#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery

#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media