sonata_admin:
    title:      SOCOTEC
    title_logo: logo/SOCOTEC.png
    assets:
        extra_stylesheets:
            - css/styles.css
        extra_javascripts:
            - js/checkbox.js
    dashboard:
        groups:
            operations:
                on_top: true
                label:                Operation
                label_catalogue:      ~
                items:
                    - admin.operation
                icon:  <i class="fa fa-briefcase"></i>

sonata_core:
    form:
        mapping:
            enabled: false
    form_type: horizontal

sonata_block:
    default_contexts: [socotec]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.search_result:
        sonata.admin.block.admin_list:
            contexts: [admin]

