sonata_core:
    form:
        mapping:
            enabled: false
    form_type: horizontal

sonata_block:
    default_contexts: [socotec]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

