sonata_admin:
    title:      SOCOTEC - ATACO
    title_logo: logo/SOCOTEC.png
    assets:
        extra_stylesheets:
            - css/styles.css
            - css/jquery-ui.min.css
        extra_javascripts:
            - js/main.js
            - js/jquery-ui.min.js
    dashboard:
        groups:
            operations:
                on_top: true
                label:                Opération
                label_catalogue:      ~
                items:
                    - admin.operation
                icon:  <i class="fa fa-briefcase"></i>
            agencies:
                on_top: true
                label:                Agence
                label_catalogue:      ~
                items:
                    - admin.agency
                icon:  <i class="fa fa-building"></i>

sonata_core:
    form:
        mapping:
            enabled: false
    form_type: horizontal

sonata_block:
    default_contexts: [socotec]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.search_result:
        sonata.admin.block.admin_list:
            contexts: [admin]

